Adding layout classes via props, and including defaults taylored to u…
GetDKAN/data-catalog-app pull request #57
Opened 2021-02-22 15:50 UTC by alexiscott

…swds.

2021-02-23 15:29 UTC, alexiscott commented
Adding a couple of Jest tests.

2021-02-23 18:49 UTC, alexiscott commented
On Second thoughts, I'm not sure how useful test would be for these classes. They are pretty arbitrary. 

There is a another piece that I think might warrant it's own ticket: Adding breakpoints as per the the existing site, and ensuring that the container applies those for max-width.

Let me know your thoughts @dgading ? And if there are any stones left unturned here?

2021-02-23 22:27 UTC, dgading requested changes
If you can just remove the container config and then on each page swap out the dc-page and config.container with the grid-container class. That extra step isn't really saving us anything and just makes it more complicated to possibly change a single page as we could break other pages when messing with config. If we had a lot pages it would make sense, but we only have like 5 pages to deal with.

2021-02-23 22:27 UTC, dgading commented on src/assets/config.json
> +  "container": "grid-container",
I would just remove this line completely. We should move to inline classes to better handle possible one off things.

2021-02-24 23:29 UTC, dgading approved these changes
Looks good!

2021-02-24 23:30 UTC, merged